version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    container_name: citybike_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   ports:
  #     - '8080:8080'
volumes:
  db:
    driver: local
